"""Add ClubRoleRegistration model

Revision ID: 613800beeb9d
Revises: 
Create Date: 2025-07-28 23:49:19.513507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613800beeb9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ClubRoleRegistration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mail', sa.String(length=120), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('dept', sa.String(length=100), nullable=False),
    sa.Column('wingname', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('experience', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ClubRoleRegistration')
    # ### end Alembic commands ###
